### ISSUE TITLE
$Song_name is not available in your country

### ISSUE THREAD

**Issue by mane** [christophior/yfitops#3]
Hi there,

I've tried your tool but for every song I'm trying to download, I get the following message:

Given URI is a Spotify track...
    $Song_name.mp3 is not available in your country

Any idea how I could fix that?

Thank you,
mane

**Comment by christophior** [comment]
I looked a little bit into this but couldn't find a definite solution. This issue would be with the module that's being used, I use my own fork of it with very minor changes but if you're still having issues I would check out https://github.com/TooTallNate/node-spotify-web and see if anyone is facing the same thing and has a fix. 

My local run works most of the time but I myself also get the `not available in your country` message for random songs.
